version: "3s"

services:
  postgres:
    image: postgres
    container_name: postgres
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=fastapi_test
    volumes:
      - postgres:/var/lib/postgresql/data
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - ./.env
    volumes:
      - ./:/app:ro
volumes:
  postgres:
