[tool.ruff]
select = [
    "E", # pycodestyle
    "F", # pyflakes
    "UP", # pyupgrade
    "I", # isort
    "COM", # flake8-commas
    "W", # pycodestyle
]

fixable = ["I", "UP", "COM", "W"]
show-fixes = true
force-exclude = true
line-length = 120
target-version = "py310"
extend-exclude = ["./alembic", "./.vscode", "./.devcontainer", "Dockerfile"]
extend-ignore = [
    'E402',
    'E722',
    'W191',
    'W293',
    'C901'
]
[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]

[tool.black]
line-length = 120
target-version = ['py310']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | data
  | notebooks
  | dist
  | alembic
  | \.devcontainer
  | \.vscode
  # The following are specific to Black, you probably don't want those.
  | blib2to3
  | tests/data
  | profiling
)/
'''